version: "3.9"

services:
  bot:
    image: discord_bot:latest
    secrets:
      - token
    environment: 
      TOKEN: /run/secrets/token
      DUMMY: Stuff

secrets:
  token:
    external: true

  